name: Android

on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-android-20200422191843-e2c3f83
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./build.sh mono+libs -os Android -arch arm64
