name: Android

on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-android-20200422191843-e2c3f83
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./build.sh mono+libs -os Android -arch arm64
      - uses: actions/upload-artifact@v3
        with:
          name: mono android-arm64
          path: artifacts/bin/microsoft.netcore.app.runtime.android-arm64/Debug/runtimes/android-arm64/
